### ISSUE TITLE
mock 没有生效，请求不到数据

### ISSUE THREAD

**Issue by taoyao-code** [iceqing/react-amis-admin#12]
直接下载，然后运行。API无法请求到mock数据

**Comment by iceqing** [comment]
vite分支吗？还是webpack分支？有没有`npm install`相关依赖？

**Comment by taoyao-code** [comment]
vite 分支，依赖下载了

**Comment by iceqing** [comment]
排查原因是/api/menus接口mock配置有问题，已经在`vite`分支进行了修复，感谢反馈！
