### ISSUE TITLE
打包后，点击复制会报错。

### ISSUE THREAD

**Issue by taoyao-code** [iceqing/react-amis-admin#13]
<img width="1339" alt="image" src="https://user-images.githubusercontent.com/38855041/191397417-e499c2a6-e59a-4e0f-977e-58430b9c472a.png">

**Comment by iceqing** [comment]
应该是`copy-to-clipboard`的问题，对vite有兼容性问题，最新`vite`分支及示例网站已修复该问题。

**Comment by iceqing** [comment]
修复代码diff：
https://github.com/iceqing/react-amis-admin/commit/919321591607f8d08c93c1b8c2582329e5325b8d
https://github.com/iceqing/react-amis-admin/commit/75e84bb5e8d3174e74505f951fe75e20393841fc
