### ISSUE TITLE
mobx有冲突？

### ISSUE THREAD

**Issue by lovefrr** [iceqing/react-amis-admin#16]
mobx.module.js:29 Uncaught Error: [mobx] There are multiple, different versions of MobX active. Make sure MobX is loaded only once or use `configure({ isolateGlobalState: true })`
    at invariant (mobx.module.js:29:15)
    at fail2 (mobx.module.js:24:5)
    at mobx.module.js:1489:17

**Comment by iceqing** [comment]
mobx确实有点问题，不过暂时应该不影响主要功能，我来解决下，多谢反馈

**Comment by iceqing** [comment]
已修复 https://github.com/iceqing/react-amis-admin/commit/9019caf589f04437678d89dabb935887c358f14e
