### ISSUE TITLE
日期显示英文

### ISSUE THREAD

**Issue by taoyao-code** [iceqing/react-amis-admin#17]
<img width="279" alt="image" src="https://user-images.githubusercontent.com/38855041/216245682-82b6f174-8c33-4582-b7db-82db37f8cf9f.png">

设置的中文，却显示英文

**Comment by iceqing** [comment]
可以贴下amis `JSON`的代码吗？

**Comment by taoyao-code** [comment]
> 

示例中的时间都是这种的。

**Comment by taoyao-code** [comment]
```json
{
  "type": "page",
  "body": {
    "type": "form",
    "debug": true,
    "api": "/amis/api/mock2/form/saveForm",
    "body": [
      {
        "type": "input-datetime",
        "name": "datetime",
        "label": "日期时间"
      }
    ]
  }
}
```

当前项目的示例中：
https://github.com/iceqing/react-amis-admin/blob/vite/src/pages/admin/form/Basic.tsx
<img width="695" alt="image" src="https://user-images.githubusercontent.com/38855041/216490435-20430a86-0876-4d74-8e20-5eade38d3143.png">

**Comment by iceqing** [comment]
这个应该是`moment`包的问题，可以在`App.tsx`引入中文文件。

```
import "moment/dist/locale/zh-cn";
```

**Comment by iceqing** [comment]
vite分支已修复该问题, 代码diff可以参考https://github.com/iceqing/react-amis-admin/commit/a205b7c75533200d4851b681cca0e9a5d00e2bd9


<img width="955" alt="image" src="https://user-images.githubusercontent.com/39587710/216519738-c4f08675-38b0-4799-a0fd-c5eb7b6e5473.png">
