### ISSUE TITLE
登录页面 axios 登录请求 不走代理

### ISSUE THREAD

**Issue by csx-bill** [iceqing/react-amis-admin#19]
登录页面 axios 登录请求 不走代理

**Comment by iceqing** [comment]
axios是没有配置走代理的，只是配置了mock，可以移除对应的mock文件，即：mock/api/login.json。如需定制，可以将登录接口改为自己的服务接口。

**Comment by csx-bill** [comment]
更换成自己的后台接口，也不会走代理

**Comment by csx-bill** [comment]
post 请求就不行，get 请求可以

**Comment by csx-bill** [comment]
你可以验证试试

**Comment by iceqing** [comment]
是vite分支吗？可以考虑移除下mock，重新试试看你的post接口是否正常。如果还是不行那应该不是mock的问题，是接口配置问题。我通过构建完成后的dist文件部署到nginx也都是正常的。


移除的mock代码位置：
`vite.config.js` 的16行`viteEasyMock()`。


另外,如果想配置代理可以参考这个issue: https://github.com/iceqing/react-amis-admin/issues/14
