### ISSUE TITLE
登录验证怎么操作？

### ISSUE THREAD

**Issue by aron0524** [iceqing/react-amis-admin#2]
项目启动就到dashboard界面了。
没登录也可以进去。

**Comment by iceqing** [comment]
之前为了方便展示，默认页面是Dashboard组件, 目前已修改为Login。同时增加了requestInterceptor.ts来做全局接口拦截。

示例页面也已更新 https://amis.iceq.cc

**Comment by aron0524** [comment]
没有登录依然可以访问 https://amis.iceq.cc/dashboard
右上角不能退出.
登录以后一直访问 https://amis.iceq.cc/api/menus这个接口

**Comment by aron0524** [comment]
chrome  93.0.4577.63

**Comment by iceqing** [comment]
已修复，可以清空下缓存并重新硬性加载试下。

**Comment by aron0524** [comment]
牛x plus。
