### ISSUE TITLE
svg 注册为amis Icon 有问题

### ISSUE THREAD

**Issue by csx-bill** [iceqing/react-amis-admin#21]
![image](https://github.com/iceqing/react-amis-admin/assets/31872268/966e391a-be43-4af8-a7b4-162b17586d63)
![image](https://github.com/iceqing/react-amis-admin/assets/31872268/86f95388-9bd5-4413-a7b2-4fb2513bfaa5)

**Comment by iceqing** [comment]
应该是缺少vite插件引起的，我再最新的代码添加了vite svg插件, 并添加了示例的自定义图标代码
https://github.com/iceqing/react-amis-admin/commit/a3c409269fa5157cbed32bb57a625e25ce51e563

**Comment by csx-bill** [comment]
AMisRenderer&nbsp; 如何增加&nbsp;

props 参数传递
例如官方的这个 ，我在你这个demo 中 尝试 传递props ,但是无法取值到


() =&gt;   renderAmis(schema, {     data: {       username: 'amis'     }   });




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Spencer ***@***.***&gt;; 
发送时间: 2023年6月25日(星期天) 晚上7:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [iceqing/react-amis-admin] svg 注册为amis Icon 有问题 (Issue #21)





 
应该是缺少vite插件引起的，我再最新的代码添加了vite svg插件, 并添加了示例的自定义图标代码
 a3c4092
