### ISSUE TITLE
使用 crud 组件 新事件 删除 请求 

### ISSUE THREAD

**Issue by csx-bill** [iceqing/react-amis-admin#24]
![image](https://github.com/iceqing/react-amis-admin/assets/31872268/c21753f2-cfcc-4218-a8a1-1b29fb8e9e0b)

![image](https://github.com/iceqing/react-amis-admin/assets/31872268/da8814b3-fbe6-44c4-801f-8a304f6ad7a4)

![image](https://github.com/iceqing/react-amis-admin/assets/31872268/465b2fb8-c6be-467c-a409-a182f11099e3)

![image](https://github.com/iceqing/react-amis-admin/assets/31872268/7ae9b600-271a-484f-982a-56848e637102)

**Comment by iceqing** [comment]
这里notify只是将异常打印了出来，并不是导致异常的原因。看图片报错，应该是editor实现ajax请求的代码，导致的异常，可以到amis-editor里提相关issue
