### ISSUE TITLE
Error after npm run dev

### ISSUE THREAD

**Issue by abasse** [iceqing/react-amis-admin#27]
I receive following error in the browser console after running:
npm i 
npm run dev

<img width="1145" alt="image" src="https://github.com/iceqing/react-amis-admin/assets/3475978/95da7fb3-1890-497d-937a-454b56a4b027">

It is also not possible to run a form in debug mode:

`import schema2component from "@/utils/schema2component";

const schema = {
  "type": "page",
  "body": {
    "type": "form",
    "title": "用户信息",
    "debug": true,
    "debugConfig": {
      "enableClipboard": true,
      "displayDataTypes": true
    },
    "body": [
      {
        "type": "input-text",
        "name": "name",
        "label": "姓名"
      },
      {
        "type": "input-email",
        "name": "email",
        "label": "邮箱"
      }
    ]
  }
}

export default schema2component(schema);`

<img width="1084" alt="image" src="https://github.com/iceqing/react-amis-admin/assets/3475978/0154e917-d21a-47ee-9cc4-c90b4402cfd8">

**Comment by iceqing** [comment]
It might be an issue with amis. Rolling back to 3.2.0 made it work normally. I've already rolled back the code in the vite branch.

可能是amis的问题，amis退回到`3.2.0`就正常了，我已经在vite分支回滚了代码

**Comment by iceqing** [comment]
https://github.com/baidu/amis/issues/8119

**Comment by abasse** [comment]
Thanks, I rolled back to 3.2.0 and the code works as expected. Thanks for the prompt response!
