### ISSUE TITLE
引入antd组件后为什么antd样式都被覆盖了，有什么解决办法吗?

### ISSUE THREAD

**Issue by yywx1220** [iceqing/react-amis-admin#29]

**Comment by iceqing** [comment]
仓库默认已经集成了antd 5.x, 不需要再额外引入了。
还有问题的话，可以提供下具体的分支，引入antd组件的版本, 具体出问题的样式图片

**Comment by yywx1220** [comment]
> 仓库默认已经集成了antd 5.x, 不需要再额外引入了。 还有问题的话，可以提供下具体的分支，引入antd组件的版本, 具体出问题的样式图片

我用的是webpack分支，用 import { Input } from "antd"   还是 import { Input } from "amis" 呢?

**Comment by iceqing** [comment]
webpack使用的是4.x的antd, 采用这种形式引入antd
`import { Input } from "antd"`

**Comment by yywx1220** [comment]
我在pages文件夹下的Login.tsx文件，引入一个antd的Input组件，界面显示的是原生input样式，没有antd的样式。

**Comment by yywx1220** [comment]
> webpack使用的是4.x的antd, 采用这种形式引入antd `import { Input } from "antd"`

请问我下了代码之后，npm install， 然后在Login.tsx文件中引入antd的Input组件，显示出来的Input输入框没有antd的样式，是否还要加什么配置呢?

**Comment by iceqing** [comment]
感谢反馈，应该是webpack分支漏引入antd样式文件了，我已经在webpack分支添加了样式文件，可以更新下最新代码。代码参考：https://github.com/iceqing/react-amis-admin/commit/9fd10351202951b7b9d279d86734a4569c2cb027
后续有时间我再优化下代码，升级下antd组件到5.x，改为按需加载样式。
