### ISSUE TITLE
vite分支使用yarn安装后，Dashboard的图表无法显示

### ISSUE THREAD

**Issue by hxj0x** [iceqing/react-amis-admin#3]
![image](https://user-images.githubusercontent.com/53702200/159489670-db69fca8-3cc7-432c-952e-c909c368193f.png)

**Comment by iceqing** [comment]
目前`vite`对于`dynamic require of xxx`支持不是特别好，目前暂未发现较好的解决方案，暂时决定等后续amis支持esm后再进行支持vite。

类似问题：https://github.com/vitejs/vite/issues/5308 , 但是提供的解决方案`vite-plugin-commonjs`对amis不生效

**同时为了加快编译**，master分支webpack已支持`HMR`功能。
第一次启动后，如果更改`amis`代码，一般都会在2s内完成编译，欢迎试用。

**Comment by duqingyu** [comment]
大佬 现在vite有继续研究吗，我也是遇到这个问题，试了尤大的方案集成monaco-editor后还是报这个错

**Comment by iceqing** [comment]
@hxj0x 这个问题已经修复了，可以尝试最新`vite`分支。

由于`amis` 2.0已经支持了`esm`，但是2.0的amis对chart的实现仍然有一些bug。 
我已经给amis官方提了个PR，参考 https://github.com/baidu/amis/pull/4904

不过我临时利用`patch-package`在本项目修复了该问题，目前可以使用vite分支来验证。
