### ISSUE TITLE
修改接口请求域名

### ISSUE THREAD

**Issue by zhuqiming** [iceqing/react-amis-admin#35]
如何自定义api请求的接口地址域名，项目启动默认是localhost:4000, 但是后端服务监听8080端口提供api接口，目前配置一个api:/a/b,完整请求地址：http://127.0.0.1:4000/a/b，如何调整成http://127.0.0.1:8080/a/b

**Comment by cstongwei** [comment]
可以配置代理。在vite.config.js文件里添加配置
  proxy: {
                "/admin": {
                    target: env.VITE_API_URL,
                    // target: "http://127.0.0.1:8050/",
                    changeOrigin: true,
                    rewrite: (path) => path,
                },
            }
![image](https://github.com/iceqing/react-amis-admin/assets/15072550/c8c6a022-8b84-4a74-a76f-e172d01d08f6)
