### ISSUE TITLE
部分样式缺失解决办法

### ISSUE THREAD

**Issue by ggymzz** [iceqing/react-amis-admin#4]
amis正确的样式如下：
// import styles
import 'amis/lib/themes/default.css';
import 'amis/lib/themes/antd.css';
import '@fortawesome/fontawesome-free/css/all.min.css';
import '@fortawesome/fontawesome-free/css/v4-shims.css';

**Comment by iceqing** [comment]
多谢建议，目前已经修复完善了`amis`部分样式问题，也欢迎提供PR， 这个问题暂时close，如果还有问题可以再次打开.
