### ISSUE TITLE
全局拦截器 code=1的情况 amis 弹窗不能自动关闭

### ISSUE THREAD

**Issue by aron0524** [iceqing/react-amis-admin#6]
requestInterceptor.ts来做全局接口拦截，code=1弹窗不能自动关闭

**Comment by iceqing** [comment]
我这验证当amis返回的错误码status=1时会在6s后自动关闭。

默认情况下amis 的error提示 6s后才会进行关闭，可以重新测试下6s后是否会关闭。

**Comment by iceqing** [comment]
如果amis的提示组件不够好，可以替换为antd的组件来进行提示，在App.tsx的63行替换为

```
notification[type] ? notification[type]({description: msg, message: type === 'error' ? '系统错误' : '系统消息'}) : console.warn('[Notify]', type, msg);
```

不过使用antd的组件`notifcation`需要文件头部`import`相关组件
```
import { notification } from 'antd';
```

**Comment by iceqing** [comment]
已经调整react-amis-admin的默认时间为`5000ms`，可以更新下代码重新试下，或者自己根据需要调整下App.tsx相关timeout等配置

**Comment by iceqing** [comment]
如果觉得`amis`的`toast`提示组件不够好，可以替换为`antd`的组件来进行提示，在App.tsx的63行替换为

```
notification[type] ? notification[type]({description: msg, message: type === 'error' ? '系统错误' : '系统消息'}) : console.warn('[Notify]', type, msg);
```

不过使用antd的组件`notifcation`需要文件头部`import`相关组件
```
import { notification } from 'antd';
```

**Comment by iceqing** [comment]
此问题已经太久未回复，临时关闭，后续有问题可以再次打开。
