### ISSUE TITLE
请问一下，这个有办法动态生成路由吗？

### ISSUE THREAD

**Issue by taoyao-code** [iceqing/react-amis-admin#7]
现在的情况是直接就加载了全部，写在前端的json数据，请问有什么办法通过后端获取json数据进行渲染吗？

**Comment by iceqing** [comment]
你的意思是不是通过接口获取动态的菜单？目前`api/menus`这个接口本地是被`mock`的，可以直接替换为后端的接口，演示网站就是从接口获取的动态菜单。

[演示网站地址](https://amis.iceq.cc/)

**Comment by taoyao-code** [comment]
是这样的，比如说，通过菜单的路径参数进行请求获取数据，然后动态显示这里的数据
<img width="1473" alt="image" src="https://user-images.githubusercontent.com/38855041/177327666-a42aaef8-c1c0-40d8-b3d1-52d23b23944d.png">
，而不是在前端写成固定的文件。
点击不同的菜单，请求，然后返回不同的数据进行展示
<img width="1471" alt="image" src="https://user-images.githubusercontent.com/38855041/177328126-2d987c3f-f0ab-4de7-9c44-04669582ff80.png">

**Comment by iceqing** [comment]
可以的，amis提供了schemaApi功能，可以从远端拉取amis json来生成界面，如果想渲染不同的界面，可以给schemaApi指定下参数，后端接口根据参数返回不同的json即可。

已经在master 分支提供了示例，可以试下：

<img width="898" alt="image" src="https://user-images.githubusercontent.com/39587710/177464150-1462ff70-a443-4d7d-a09d-3163a01152e5.png">

**Comment by taoyao-code** [comment]
好的，谢谢。
